#! /bin/sh


for app in 'combainer@1' 'parsing@1' 'aggregate@1';
do
    /usr/bin/cocaine-engine-delete $app
    rm -rf /var/lib/cocaine/apps/$app
    rm -rf /var/spool/cocaine/$app
    rm -rf /var/cache/cocaine/apps/$app
    /etc/init.d/cocaine-server reload
done
ps aux | grep startCombainer | grep -v grep | awk '{print $2}' | xargs -n1 kill -9

#DEBHELPER#
