#! /usr/bin/env python

import sys
import types

sys.path.insert(0, "/usr/lib/yandex/combaine/")


from parsers import PARSERS

available = ((name, func) for name, func in PARSERS.iteritems() if isinstance(func, types.FunctionType))

f = open(sys.argv[1]).read().splitlines()
for name, func in available:
    try:
        t = [ _ for _ in func(f)]
        if len(t) > 0:
            print name
            print t
    except Exception as err:
        pass
